services:
########## SONARR CONFIGURATION ##########
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /Users/kp-srv-01/Documents/docker/sonarr/config:/config
      - /Volumes/media/tv:/mnt/tv #optional
      - /Volumes/downloads:/mnt/downloads
    ports:
      - 30027:8989
    restart: always