services:
########## AUDIOBOOKSHELF CONFIGURATION ##########
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    ports:
      - 30033:30033
    volumes:
      - /Volumes/media/audiobooks:/audiobooks
      - /Users/kp-srv-01/Documents/docker/audiobookshelf/podcasts:/podcasts
      - /Users/kp-srv-01/Documents/docker/audiobookshelf/config:/config
      - /Users/kp-srv-01/Documents/docker/audiobookshelf/metadata:/metadata
    environment:
      - TZ=America/Chicago
    restart: unless-stopped