services:
########## HEIMDALL CONFIGURATION ##########
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /Users/kp-srv-01/Documents/docker/heimdall/config:/config
    ports:
      - 8081:80
      - 8443:443
    restart: unless-stopped
